---
kind: Service
apiVersion: v1
metadata:
  name: test-docker
spec:
  selector:
    app: test-docker
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 80
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-docker
  labels:
     app: test-docker
spec:
  selector:
    matchLabels:
      app: test-docker
  replicas: 5
  template:
    metadata:
      labels:
        app: test-docker
    spec:
      containers:
        - name: test-docker
          image: docker.io/personal123/test-docker:latest
          ports:
            - containerPort: 80